s=input()
s1 , s2 = s.split('?')
name , pwd , profile , role, key = s2.split('&')
p1 , v1 = name.split('=')
p2 , v2= pwd.split('=')
p4 , v4 = role.split('=')
p3 , v3 = profile.split('=')
p5 , v5 = key.split('=')
print(f"{p1}: {v1}\n{p2}: {v2}\n{p3}: {v3}\n{p4}: {v4}\n{p5}: {v5}")